# If you come from bash you might have to change your $PATH.   
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Android sdk
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Tmux plugin
ZSH_TMUX_UNICODE=true
ZSH_TMUX_AUTOSTART=true
# If error or no sessions exists set default session name
if ! tmux list-sessions > /dev/null 2>&1; then
  ZSH_TMUX_DEFAULT_SESSION_NAME='main'
fi

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="random"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
export HIST_STAMPS="yyyy-mm-dd"
export HISTCONTROL="ignoreboth:erasedups"     # Omit duplicates and commands that begin with a space from history.
setopt HIST_IGNORE_SPACE     # Don't record an entry starting with a space.
setopt HIST_IGNORE_ALL_DUPS  # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS      # Don't record an entry that was just recorded again.
setopt HIST_SAVE_NO_DUPS     # Don't write duplicate entries in the history file.
setopt HIST_FIND_NO_DUPS     # Do not display a line previously found.

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  tmux
  # autojump
  # zsh-autosuggestions
  zsh-syntax-highlighting
  # tldr
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim' # default is 'mvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set up asdf
. "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"
. "$HOME/.asdf/plugins/golang/set-env.zsh" # golang
. "$HOME/.asdf/plugins/java/set-java-home.zsh" # java

# Set up fzfz
source <(fzf --zsh)
export FZF_DEFAULT_OPTS="--color=fg:cyan,bg:#282828,hl:#FFD700,fg+:#00ffff,bg+:#3c3836,hl+:#B95CF4,info:#8ec07c,prompt:#fe8019,pointer:#d3869b,marker:#b8bb26,spinner:#83a598"
# export FZF_DEFAULT_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'" # Default open preview

# homebrew 
export HOMEBREW_NO_AUTO_UPDATE=1

############################
####### key bindings #######
############################
# make terminal command navigation sane again
# bindkey "^[[1;5C" forward-word                      # [Ctrl-right] - forward one word
# bindkey "^[[1;5D" backward-word                     # [Ctrl-left] - backward one word
# bindkey '^[^[[C' forward-word                       # [Ctrl-right] - forward one word
# bindkey '^[^[[D' backward-word                      # [Ctrl-left] - backward one word
# bindkey '^[[1;3D' beginning-of-line                 # [Alt-left] - beginning of line
# bindkey '^[[1;3C' end-of-line                       # [Alt-right] - end of line
# bindkey '^[[5D' beginning-of-line                   # [Alt-left] - beginning of line
# bindkey '^[[5C' end-of-line                         # [Alt-right] - end of line
# bindkey '^?' backward-delete-char                   # [Backspace] - delete backward
